mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls'), name='polls'),
    #path('/',include('polls.urls'))

]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    #path('',views.index, name='index'),
    path('',views.IndexView.as_view(), name='index'),
    #path('hola2/',views.hola_dos, name='hola2'),
    # ex: /polls/
    #path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # ex: /polls/5/edit
    path('<int:question_id>/edit/', views.add_or_change_question, name='edit'),
]

mysite/polls/models.py
from pickle import TRUE
from statistics import mode
from django.db import models
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    status = models.BooleanField(default=True)
    order = models.IntegerField(null=True)

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    def __str__(self) :
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0) 

mysite/polls/forms.py
from django import forms
from .models import Question, Choice


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = '__all__'

mysite/polls/views.py
from ast import arg
from multiprocessing import context
from django.shortcuts import render, redirect
from django.http import HttpResponse

#from mysite.polls.forms import QuestionForm
from .models import Question, Choice
from django.template import loader
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import ListView
from .forms import QuestionForm

# Create your views here.

#def index(request):
#    questions = Question.objects.all()
#    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    #output = ', '.join([q.question_text for q in latest_question_list])
    #return HttpResponse(output)
#    template = loader.get_template('polls/index.html')
#    context = {
#        'mensaje': "Lista de encuestas",
#        'latest_question_list': latest_question_list,
#    }
#    return HttpResponse(template.render(context, request))

class IndexView(ListView): 
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(*kwargs)
        context ['mensaje'] = "Lista de encuestas"
        return context


    def get_queryset(self):
        query = Question.objects.order_by('-pub_date')[:5]

        return query


def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    context = {
        'mensaje': "Detalle de la encuestas",
        'question': question,
    }
    return render(request, 'polls/detail.html', context)
    #return HttpResponse("You're looking at question %s." % question_id)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    print("hola")
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        print("guardaste el voto")
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def add_or_change_question(request, question_id=None):
    question = None
    #idea = None
    if question_id:
        question = get_object_or_404(Question, pk=question_id)
        #idea = get_object_or_404(Question, pk=pk)
        if request.method == "POST":
            form = QuestionForm(
            data=request.POST,
            files=request.FILES,
            instance=question
            )
            if form.is_valid():
                question = form.save()
                return HttpResponseRedirect(reverse('polls:detail', args=(question.id,)))
               # return redirect("polls:detail", pk=question.pk)
        else:
            form = QuestionForm(instance=question)
    context = {"question": question, "form": form}
    return render(request, "polls/polls_form.html", context)

mysite/polls/templates/polls/detail.html
<h1>{{ mensaje }}</h1>
{{ question.question_text }}
<p>Nombre de la encuesta: {{ question.question_text }}</p>
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            <h1>{{ question.question_text }}</h1>
        </legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>
<a href="{% url 'polls:edit' question.id %}">Editar encuesta</a>

mysite/polls/templates/polls/index.html
<h1>{{ mensaje }}</h1>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <!-- <li><a href= "/polls/{{ question.id }}/">{{ question.question_text }}</a></li> -->
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/polls_form.html
<a href="{% url 'polls:index' %}"> List of  encuestas</a>
<h1>
    {% if question %}
        Change Encuesta {{ question.question_text }}
    {% else %}
        Agregar encuesta
    {% endif %}
</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
<input type="submit" value="Guardar">
</form>

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>